module: rest-core
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.git/.*)|
   (.gitignore)|
   (.DS_Store)|

   (^external/nose/.*)|
   (^external/pip/.*)|
   (^'external/easy_install\.*)|
   (^external/mock\.*)|
   (^external/nose_exclude.*)|
   (^external/nosegae.*)|
   (^external/rednose.*)|
   (^external/yanc/.*)|
   (^external/setuptools/.*)|
   (^external/rsa/.*)|
   )$

builtins:
  - remote_api: on

automatic_scaling:
  min_idle_instances: 1
  max_pending_latency: 10s

handlers:
- url: .*
  script: example.main.app