# Note: This just needs to be present for GAE Testbed unit tests

module: rest-core
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: .*
  script: doesnotexist.app